In [1]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import csv
import itertools

In [2]:
with open('newdata_from_stacy.csv') as f:
    reader = csv.DictReader(f)
    data = [r for r in reader]
        

seq = []
for i in range(len(data)):
    seq.append(data[i]['Sequence'])
       

In [3]:
# alphabetical nucleotide -> integer mapping

#seq_num = np.array([sequence for sequence in seq])
seq_num = np.array([list(sequence) for sequence in seq])
seq_num = np.char.replace(seq_num, 'A', '0')
seq_num = np.char.replace(seq_num, 'C', '1')
seq_num = np.char.replace(seq_num, 'G', '2')
seq_num = np.char.replace(seq_num, 'T', '3')
seq_num = seq_num.astype(np.int)

np.savetxt('seq_num.csv', seq_num, fmt = '%1d')



In [167]:
def k_mer_motif(seq_mat,
                num_k,
                num_n = 10,
                save_or_not = True):
    # seq_mat should be a numpy matrix (batch, num_n) with 0,1,2,3 value
    # A:0 / C:1 / G:2 / T:3
    # num_n represents the length of each sequence: AGCCG -> 5
    # num_k represents the number of nucleotides in one motif: 2 -> AA/AC/AG/AT/CA ....
    # save_or_not is a switch for saving option
    
    # Create a list of motif pool. The size of pool will be 4^num_k.
    iter_pool = itertools.product('0123', repeat = num_k)
    pool = []
    for i in iter_pool:
        pool.append([int(i[j]) for j in range(num_k)])
    # Group consecutive k elements in the original dataset. [1,0,2,3,2] -> [[1,0], [0,2], [2, 3], [3, 2]]
    seq_group = []
    for i in range(seq_mat.shape[0]):
        temp = []
        for k in range(num_n-num_k+1):
            temp.append([seq_mat[i][k+j] for j in range(num_k)])
        seq_group.append(temp)
        
    # Create a blank transformed array.
    output = np.zeros((seq_mat.shape[0], num_n-num_k+1),dtype = int)

    for batch in range(seq_mat.shape[0]):
        for val in range(len(pool)):
            try:
                pos = [i for i, n in enumerate(seq_group[batch]) if n == pool[val]]
                output[batch][pos] = val

            except:
                pass
    return output
         

In [170]:
a  = k_mer_motif(seq_num, 4)
print(a)

[[163 141  55 ... 123 237 180]
 [  3  14  56 ... 134  27 109]
 [ 21  84  82 ...  47 191 252]
 ...
 [165 150  90 ... 170 169 165]
 [106 169 165 ...  90 106 168]
 [149  86  90 ... 169 165 149]]


In [100]:
seq_mod = np.array([sequence for sequnece in seq])
seq_mod = np.char.replace(seq_mod, 'A', '0')
seq_mod = np.char.replace(seq_mod, 'C', '1')
seq_mod = np.char.replace(seq_mod, 'G', '2')
seq_mod = np.char.replace(seq_mod, 'T', '3')
a = np.where(seq_num ==[0, 0])
print(a)

(array([], dtype=int64),)


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:7: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  import sys


In [87]:
onehot_encoder = OneHotEncoder(sparse = False)
seq_num_onehot = onehot_encoder.fit_transform(seq_num)
seq_num_hot = np.reshape(seq_num_onehot, (-1, 10, 4))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [126]:
a[1]

[[0, 0], [0, 0], [0, 3], [3, 2], [2, 0], [0, 1], [1, 2], [2, 3], [3, 1]]

In [140]:
a[0]
aa = []
for k in range(16):
    aa.append([i for i, n in enumerate(a[0]) if n == pool2[k]])
    

In [139]:
for i, n in enumerate(a[0]):
    print(i)
    print(n)

0
[2, 2]
1
[2, 0]
2
[0, 3]
3
[3, 1]
4
[1, 3]
5
[3, 2]
6
[2, 3]
7
[3, 1]
8
[1, 0]


In [154]:
c = [1,2,3,4,5,6,7,8,9,10]
c[aa[3][0]]

3

In [142]:
a[0]

[[2, 2], [2, 0], [0, 3], [3, 1], [1, 3], [3, 2], [2, 3], [3, 1], [1, 0]]

In [143]:
pool2

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3]]

In [155]:
len(aa)

16

In [157]:
len(aa[3])

1

In [161]:
b[0]

array([10,  8,  3, 13,  7, 14, 11, 13,  4])

In [162]:
aa[0]

[]

In [163]:
aa

[[], [], [], [2], [8], [], [], [4], [1], [], [0], [6], [], [3, 7], [5], []]